#############################################################################
# Makefile for building: blade
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  ../blade/blade.pro
# Template: app
# Command: /home/tyler/Qt/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile ../blade/blade.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../blade -I. -I../Qt/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /home/tyler/Qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = blade1.0.0
DISTDIR = /home/tyler/blade/.tmp/blade1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/tyler/Qt/5.4/gcc_64
LIBS          = $(SUBLIBS) -pthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../blade/main.cpp \
		../blade/gps.cpp \
		../blade/mower.cpp \
		../blade/WaypointNavigation.cpp \
		../blade/motordriver.cpp \
		../blade/joystick.cpp \
		../blade/ManualControl.cpp \
		../blade/controlserver.cpp \
		../blade/ultrasonic.cpp \
		../blade/libGPIO/libgpio.cpp \
		../blade/NMEAParser/NMEAParser.cpp \
		../blade/serialport.cpp \
		../blade/lawnmap.cpp \
		../blade/quadtree.cpp \
		../blade/global.cpp 
OBJECTS       = main.o \
		gps.o \
		mower.o \
		WaypointNavigation.o \
		motordriver.o \
		joystick.o \
		ManualControl.o \
		controlserver.o \
		ultrasonic.o \
		libgpio.o \
		NMEAParser.o \
		serialport.o \
		lawnmap.o \
		quadtree.o \
		global.o
DIST          = gps.h \
		motordriver.h \
		mower.h \
		joystick.h \
		controlserver.h \
		ultrasonic.h \
		libgpio.h \
		libGPIO/libgpio.h \
		NMEAParser/NMEAParser.h \
		serialport.h \
		lawnmap.h \
		quadtree.h \
		global.h ../blade/main.cpp \
		../blade/gps.cpp \
		../blade/mower.cpp \
		../blade/WaypointNavigation.cpp \
		../blade/motordriver.cpp \
		../blade/joystick.cpp \
		../blade/ManualControl.cpp \
		../blade/controlserver.cpp \
		../blade/ultrasonic.cpp \
		../blade/libGPIO/libgpio.cpp \
		../blade/NMEAParser/NMEAParser.cpp \
		../blade/serialport.cpp \
		../blade/lawnmap.cpp \
		../blade/quadtree.cpp \
		../blade/global.cpp

DESTDIR       = #avoid trailing-slash linebreak
TARGET        = blade


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

all: Makefile $(TARGET)

clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core

####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: ../blade/main.cpp ../blade/mower.h \
		../blade/gps.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../blade/main.cpp

gps.o: ../blade/gps.cpp ../blade/gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gps.o ../blade/gps.cpp

mower.o: ../blade/mower.cpp ../blade/mower.h \
		../blade/gps.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mower.o ../blade/mower.cpp

WaypointNavigation.o: ../blade/WaypointNavigation.cpp ../blade/mower.h \
		../blade/gps.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaypointNavigation.o ../blade/WaypointNavigation.cpp

motordriver.o: ../blade/motordriver.cpp ../blade/mower.h \
		../blade/gps.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o motordriver.o ../blade/motordriver.cpp

joystick.o: ../blade/joystick.cpp ../blade/joystick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o joystick.o ../blade/joystick.cpp

ManualControl.o: ../blade/ManualControl.cpp ../blade/mower.h \
		../blade/gps.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManualControl.o ../blade/ManualControl.cpp

controlserver.o: ../blade/controlserver.cpp ../blade/controlserver.h \
		../blade/gps.h \
		../blade/mower.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlserver.o ../blade/controlserver.cpp

ultrasonic.o: ../blade/ultrasonic.cpp ../blade/mower.h \
		../blade/gps.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ultrasonic.o ../blade/ultrasonic.cpp

libgpio.o: ../blade/libGPIO/libgpio.cpp ../blade/libGPIO/libgpio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libgpio.o ../blade/libGPIO/libgpio.cpp

NMEAParser.o: ../blade/NMEAParser/NMEAParser.cpp ../blade/NMEAParser/NMEAParser.h \
		../blade/gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NMEAParser.o ../blade/NMEAParser/NMEAParser.cpp

serialport.o: ../blade/serialport.cpp ../blade/serialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialport.o ../blade/serialport.cpp

lawnmap.o: ../blade/lawnmap.cpp ../blade/lawnmap.h \
		../blade/gps.h \
		../blade/mower.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lawnmap.o ../blade/lawnmap.cpp

quadtree.o: ../blade/quadtree.cpp ../blade/quadtree.h \
		../blade/lawnmap.h \
		../blade/gps.h \
		../blade/mower.h \
		../blade/motordriver.h \
		../blade/serialport.h \
		../blade/joystick.h \
		../blade/controlserver.h \
		../blade/ultrasonic.h \
		../blade/libGPIO/libgpio.h \
		../blade/NMEAParser/NMEAParser.h \
		../blade/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quadtree.o ../blade/quadtree.cpp

global.o: ../blade/global.cpp ../blade/global.h \
		../blade/gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o global.o ../blade/global.cpp
